# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quotes',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
