# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180329_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotes',
            new_name='content',
        ),
    ]
