# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180330_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='first_app.User'),
        ),
    ]
