# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_quote_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
